
#ifndef TRANSFORMPLUGIN001_EXPORT_H
#define TRANSFORMPLUGIN001_EXPORT_H

#ifdef TRANSFORMPLUGIN001_STATIC_DEFINE
#  define TRANSFORMPLUGIN001_EXPORT
#  define TRANSFORMPLUGIN001_NO_EXPORT
#else
#  ifndef TRANSFORMPLUGIN001_EXPORT
#    ifdef transformPlugin001_EXPORTS
        /* We are building this library */
#      define TRANSFORMPLUGIN001_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define TRANSFORMPLUGIN001_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef TRANSFORMPLUGIN001_NO_EXPORT
#    define TRANSFORMPLUGIN001_NO_EXPORT 
#  endif
#endif

#ifndef TRANSFORMPLUGIN001_DEPRECATED
#  define TRANSFORMPLUGIN001_DEPRECATED __declspec(deprecated)
#endif

#ifndef TRANSFORMPLUGIN001_DEPRECATED_EXPORT
#  define TRANSFORMPLUGIN001_DEPRECATED_EXPORT TRANSFORMPLUGIN001_EXPORT TRANSFORMPLUGIN001_DEPRECATED
#endif

#ifndef TRANSFORMPLUGIN001_DEPRECATED_NO_EXPORT
#  define TRANSFORMPLUGIN001_DEPRECATED_NO_EXPORT TRANSFORMPLUGIN001_NO_EXPORT TRANSFORMPLUGIN001_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef TRANSFORMPLUGIN001_NO_DEPRECATED
#    define TRANSFORMPLUGIN001_NO_DEPRECATED
#  endif
#endif

#endif /* TRANSFORMPLUGIN001_EXPORT_H */
