
#ifndef SEGMENTATIONPLUGIN001_EXPORT_H
#define SEGMENTATIONPLUGIN001_EXPORT_H

#ifdef SEGMENTATIONPLUGIN001_STATIC_DEFINE
#  define SEGMENTATIONPLUGIN001_EXPORT
#  define SEGMENTATIONPLUGIN001_NO_EXPORT
#else
#  ifndef SEGMENTATIONPLUGIN001_EXPORT
#    ifdef segmentationPlugin001_EXPORTS
        /* We are building this library */
#      define SEGMENTATIONPLUGIN001_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define SEGMENTATIONPLUGIN001_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef SEGMENTATIONPLUGIN001_NO_EXPORT
#    define SEGMENTATIONPLUGIN001_NO_EXPORT 
#  endif
#endif

#ifndef SEGMENTATIONPLUGIN001_DEPRECATED
#  define SEGMENTATIONPLUGIN001_DEPRECATED __declspec(deprecated)
#endif

#ifndef SEGMENTATIONPLUGIN001_DEPRECATED_EXPORT
#  define SEGMENTATIONPLUGIN001_DEPRECATED_EXPORT SEGMENTATIONPLUGIN001_EXPORT SEGMENTATIONPLUGIN001_DEPRECATED
#endif

#ifndef SEGMENTATIONPLUGIN001_DEPRECATED_NO_EXPORT
#  define SEGMENTATIONPLUGIN001_DEPRECATED_NO_EXPORT SEGMENTATIONPLUGIN001_NO_EXPORT SEGMENTATIONPLUGIN001_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SEGMENTATIONPLUGIN001_NO_DEPRECATED
#    define SEGMENTATIONPLUGIN001_NO_DEPRECATED
#  endif
#endif

#endif /* SEGMENTATIONPLUGIN001_EXPORT_H */
