
#ifndef FILTERPLUGIN001_EXPORT_H
#define FILTERPLUGIN001_EXPORT_H

#ifdef FILTERPLUGIN001_STATIC_DEFINE
#  define FILTERPLUGIN001_EXPORT
#  define FILTERPLUGIN001_NO_EXPORT
#else
#  ifndef FILTERPLUGIN001_EXPORT
#    ifdef filterPlugin001_EXPORTS
        /* We are building this library */
#      define FILTERPLUGIN001_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define FILTERPLUGIN001_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef FILTERPLUGIN001_NO_EXPORT
#    define FILTERPLUGIN001_NO_EXPORT 
#  endif
#endif

#ifndef FILTERPLUGIN001_DEPRECATED
#  define FILTERPLUGIN001_DEPRECATED __declspec(deprecated)
#endif

#ifndef FILTERPLUGIN001_DEPRECATED_EXPORT
#  define FILTERPLUGIN001_DEPRECATED_EXPORT FILTERPLUGIN001_EXPORT FILTERPLUGIN001_DEPRECATED
#endif

#ifndef FILTERPLUGIN001_DEPRECATED_NO_EXPORT
#  define FILTERPLUGIN001_DEPRECATED_NO_EXPORT FILTERPLUGIN001_NO_EXPORT FILTERPLUGIN001_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef FILTERPLUGIN001_NO_DEPRECATED
#    define FILTERPLUGIN001_NO_DEPRECATED
#  endif
#endif

#endif /* FILTERPLUGIN001_EXPORT_H */
