
#ifndef MEDIANFILTERPLUGIN001_EXPORT_H
#define MEDIANFILTERPLUGIN001_EXPORT_H

#ifdef MEDIANFILTERPLUGIN001_STATIC_DEFINE
#  define MEDIANFILTERPLUGIN001_EXPORT
#  define MEDIANFILTERPLUGIN001_NO_EXPORT
#else
#  ifndef MEDIANFILTERPLUGIN001_EXPORT
#    ifdef medianFilterPlugin001_EXPORTS
        /* We are building this library */
#      define MEDIANFILTERPLUGIN001_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MEDIANFILTERPLUGIN001_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MEDIANFILTERPLUGIN001_NO_EXPORT
#    define MEDIANFILTERPLUGIN001_NO_EXPORT 
#  endif
#endif

#ifndef MEDIANFILTERPLUGIN001_DEPRECATED
#  define MEDIANFILTERPLUGIN001_DEPRECATED __declspec(deprecated)
#endif

#ifndef MEDIANFILTERPLUGIN001_DEPRECATED_EXPORT
#  define MEDIANFILTERPLUGIN001_DEPRECATED_EXPORT MEDIANFILTERPLUGIN001_EXPORT MEDIANFILTERPLUGIN001_DEPRECATED
#endif

#ifndef MEDIANFILTERPLUGIN001_DEPRECATED_NO_EXPORT
#  define MEDIANFILTERPLUGIN001_DEPRECATED_NO_EXPORT MEDIANFILTERPLUGIN001_NO_EXPORT MEDIANFILTERPLUGIN001_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef MEDIANFILTERPLUGIN001_NO_DEPRECATED
#    define MEDIANFILTERPLUGIN001_NO_DEPRECATED
#  endif
#endif

#endif /* MEDIANFILTERPLUGIN001_EXPORT_H */
