
#ifndef TEMPLATEPLUGIN002_EXPORT_H
#define TEMPLATEPLUGIN002_EXPORT_H

#ifdef TEMPLATEPLUGIN002_STATIC_DEFINE
#  define TEMPLATEPLUGIN002_EXPORT
#  define TEMPLATEPLUGIN002_NO_EXPORT
#else
#  ifndef TEMPLATEPLUGIN002_EXPORT
#    ifdef templatePlugin002_EXPORTS
        /* We are building this library */
#      define TEMPLATEPLUGIN002_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define TEMPLATEPLUGIN002_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef TEMPLATEPLUGIN002_NO_EXPORT
#    define TEMPLATEPLUGIN002_NO_EXPORT 
#  endif
#endif

#ifndef TEMPLATEPLUGIN002_DEPRECATED
#  define TEMPLATEPLUGIN002_DEPRECATED __declspec(deprecated)
#endif

#ifndef TEMPLATEPLUGIN002_DEPRECATED_EXPORT
#  define TEMPLATEPLUGIN002_DEPRECATED_EXPORT TEMPLATEPLUGIN002_EXPORT TEMPLATEPLUGIN002_DEPRECATED
#endif

#ifndef TEMPLATEPLUGIN002_DEPRECATED_NO_EXPORT
#  define TEMPLATEPLUGIN002_DEPRECATED_NO_EXPORT TEMPLATEPLUGIN002_NO_EXPORT TEMPLATEPLUGIN002_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef TEMPLATEPLUGIN002_NO_DEPRECATED
#    define TEMPLATEPLUGIN002_NO_DEPRECATED
#  endif
#endif

#endif /* TEMPLATEPLUGIN002_EXPORT_H */
