
#ifndef FOURIERPLUGIN002_EXPORT_H
#define FOURIERPLUGIN002_EXPORT_H

#ifdef FOURIERPLUGIN002_STATIC_DEFINE
#  define FOURIERPLUGIN002_EXPORT
#  define FOURIERPLUGIN002_NO_EXPORT
#else
#  ifndef FOURIERPLUGIN002_EXPORT
#    ifdef fourierPlugin002_EXPORTS
        /* We are building this library */
#      define FOURIERPLUGIN002_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define FOURIERPLUGIN002_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef FOURIERPLUGIN002_NO_EXPORT
#    define FOURIERPLUGIN002_NO_EXPORT 
#  endif
#endif

#ifndef FOURIERPLUGIN002_DEPRECATED
#  define FOURIERPLUGIN002_DEPRECATED __declspec(deprecated)
#endif

#ifndef FOURIERPLUGIN002_DEPRECATED_EXPORT
#  define FOURIERPLUGIN002_DEPRECATED_EXPORT FOURIERPLUGIN002_EXPORT FOURIERPLUGIN002_DEPRECATED
#endif

#ifndef FOURIERPLUGIN002_DEPRECATED_NO_EXPORT
#  define FOURIERPLUGIN002_DEPRECATED_NO_EXPORT FOURIERPLUGIN002_NO_EXPORT FOURIERPLUGIN002_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef FOURIERPLUGIN002_NO_DEPRECATED
#    define FOURIERPLUGIN002_NO_DEPRECATED
#  endif
#endif

#endif /* FOURIERPLUGIN002_EXPORT_H */
