
#ifndef OPENCVINTERFACE002_EXPORT_H
#define OPENCVINTERFACE002_EXPORT_H

#ifdef OPENCVINTERFACE002_STATIC_DEFINE
#  define OPENCVINTERFACE002_EXPORT
#  define OPENCVINTERFACE002_NO_EXPORT
#else
#  ifndef OPENCVINTERFACE002_EXPORT
#    ifdef openCVInterface002_EXPORTS
        /* We are building this library */
#      define OPENCVINTERFACE002_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define OPENCVINTERFACE002_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef OPENCVINTERFACE002_NO_EXPORT
#    define OPENCVINTERFACE002_NO_EXPORT 
#  endif
#endif

#ifndef OPENCVINTERFACE002_DEPRECATED
#  define OPENCVINTERFACE002_DEPRECATED __declspec(deprecated)
#endif

#ifndef OPENCVINTERFACE002_DEPRECATED_EXPORT
#  define OPENCVINTERFACE002_DEPRECATED_EXPORT OPENCVINTERFACE002_EXPORT OPENCVINTERFACE002_DEPRECATED
#endif

#ifndef OPENCVINTERFACE002_DEPRECATED_NO_EXPORT
#  define OPENCVINTERFACE002_DEPRECATED_NO_EXPORT OPENCVINTERFACE002_NO_EXPORT OPENCVINTERFACE002_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef OPENCVINTERFACE002_NO_DEPRECATED
#    define OPENCVINTERFACE002_NO_DEPRECATED
#  endif
#endif

#endif /* OPENCVINTERFACE002_EXPORT_H */
