
#ifndef COLORPLUGIN001_EXPORT_H
#define COLORPLUGIN001_EXPORT_H

#ifdef COLORPLUGIN001_STATIC_DEFINE
#  define COLORPLUGIN001_EXPORT
#  define COLORPLUGIN001_NO_EXPORT
#else
#  ifndef COLORPLUGIN001_EXPORT
#    ifdef colorPlugin001_EXPORTS
        /* We are building this library */
#      define COLORPLUGIN001_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define COLORPLUGIN001_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef COLORPLUGIN001_NO_EXPORT
#    define COLORPLUGIN001_NO_EXPORT 
#  endif
#endif

#ifndef COLORPLUGIN001_DEPRECATED
#  define COLORPLUGIN001_DEPRECATED __declspec(deprecated)
#endif

#ifndef COLORPLUGIN001_DEPRECATED_EXPORT
#  define COLORPLUGIN001_DEPRECATED_EXPORT COLORPLUGIN001_EXPORT COLORPLUGIN001_DEPRECATED
#endif

#ifndef COLORPLUGIN001_DEPRECATED_NO_EXPORT
#  define COLORPLUGIN001_DEPRECATED_NO_EXPORT COLORPLUGIN001_NO_EXPORT COLORPLUGIN001_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef COLORPLUGIN001_NO_DEPRECATED
#    define COLORPLUGIN001_NO_DEPRECATED
#  endif
#endif

#endif /* COLORPLUGIN001_EXPORT_H */
