
#ifndef TRANSFORMPLUGIN002_EXPORT_H
#define TRANSFORMPLUGIN002_EXPORT_H

#ifdef TRANSFORMPLUGIN002_STATIC_DEFINE
#  define TRANSFORMPLUGIN002_EXPORT
#  define TRANSFORMPLUGIN002_NO_EXPORT
#else
#  ifndef TRANSFORMPLUGIN002_EXPORT
#    ifdef transformPlugin002_EXPORTS
        /* We are building this library */
#      define TRANSFORMPLUGIN002_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define TRANSFORMPLUGIN002_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef TRANSFORMPLUGIN002_NO_EXPORT
#    define TRANSFORMPLUGIN002_NO_EXPORT 
#  endif
#endif

#ifndef TRANSFORMPLUGIN002_DEPRECATED
#  define TRANSFORMPLUGIN002_DEPRECATED __declspec(deprecated)
#endif

#ifndef TRANSFORMPLUGIN002_DEPRECATED_EXPORT
#  define TRANSFORMPLUGIN002_DEPRECATED_EXPORT TRANSFORMPLUGIN002_EXPORT TRANSFORMPLUGIN002_DEPRECATED
#endif

#ifndef TRANSFORMPLUGIN002_DEPRECATED_NO_EXPORT
#  define TRANSFORMPLUGIN002_DEPRECATED_NO_EXPORT TRANSFORMPLUGIN002_NO_EXPORT TRANSFORMPLUGIN002_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef TRANSFORMPLUGIN002_NO_DEPRECATED
#    define TRANSFORMPLUGIN002_NO_DEPRECATED
#  endif
#endif

#endif /* TRANSFORMPLUGIN002_EXPORT_H */
