
#ifndef COPYMAKEBORDERPLUGIN001_EXPORT_H
#define COPYMAKEBORDERPLUGIN001_EXPORT_H

#ifdef COPYMAKEBORDERPLUGIN001_STATIC_DEFINE
#  define COPYMAKEBORDERPLUGIN001_EXPORT
#  define COPYMAKEBORDERPLUGIN001_NO_EXPORT
#else
#  ifndef COPYMAKEBORDERPLUGIN001_EXPORT
#    ifdef copymakeborderPlugin001_EXPORTS
        /* We are building this library */
#      define COPYMAKEBORDERPLUGIN001_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define COPYMAKEBORDERPLUGIN001_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef COPYMAKEBORDERPLUGIN001_NO_EXPORT
#    define COPYMAKEBORDERPLUGIN001_NO_EXPORT 
#  endif
#endif

#ifndef COPYMAKEBORDERPLUGIN001_DEPRECATED
#  define COPYMAKEBORDERPLUGIN001_DEPRECATED __declspec(deprecated)
#endif

#ifndef COPYMAKEBORDERPLUGIN001_DEPRECATED_EXPORT
#  define COPYMAKEBORDERPLUGIN001_DEPRECATED_EXPORT COPYMAKEBORDERPLUGIN001_EXPORT COPYMAKEBORDERPLUGIN001_DEPRECATED
#endif

#ifndef COPYMAKEBORDERPLUGIN001_DEPRECATED_NO_EXPORT
#  define COPYMAKEBORDERPLUGIN001_DEPRECATED_NO_EXPORT COPYMAKEBORDERPLUGIN001_NO_EXPORT COPYMAKEBORDERPLUGIN001_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef COPYMAKEBORDERPLUGIN001_NO_DEPRECATED
#    define COPYMAKEBORDERPLUGIN001_NO_DEPRECATED
#  endif
#endif

#endif /* COPYMAKEBORDERPLUGIN001_EXPORT_H */
