
#ifndef OPENCVINTERFACE001_EXPORT_H
#define OPENCVINTERFACE001_EXPORT_H

#ifdef OPENCVINTERFACE001_STATIC_DEFINE
#  define OPENCVINTERFACE001_EXPORT
#  define OPENCVINTERFACE001_NO_EXPORT
#else
#  ifndef OPENCVINTERFACE001_EXPORT
#    ifdef openCVInterface001_EXPORTS
        /* We are building this library */
#      define OPENCVINTERFACE001_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define OPENCVINTERFACE001_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef OPENCVINTERFACE001_NO_EXPORT
#    define OPENCVINTERFACE001_NO_EXPORT 
#  endif
#endif

#ifndef OPENCVINTERFACE001_DEPRECATED
#  define OPENCVINTERFACE001_DEPRECATED __declspec(deprecated)
#endif

#ifndef OPENCVINTERFACE001_DEPRECATED_EXPORT
#  define OPENCVINTERFACE001_DEPRECATED_EXPORT OPENCVINTERFACE001_EXPORT OPENCVINTERFACE001_DEPRECATED
#endif

#ifndef OPENCVINTERFACE001_DEPRECATED_NO_EXPORT
#  define OPENCVINTERFACE001_DEPRECATED_NO_EXPORT OPENCVINTERFACE001_NO_EXPORT OPENCVINTERFACE001_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef OPENCVINTERFACE001_NO_DEPRECATED
#    define OPENCVINTERFACE001_NO_DEPRECATED
#  endif
#endif

#endif /* OPENCVINTERFACE001_EXPORT_H */
