
#ifndef OPENCVINTERFACE_EXPORT_H
#define OPENCVINTERFACE_EXPORT_H

#ifdef OPENCVINTERFACE_STATIC_DEFINE
#  define OPENCVINTERFACE_EXPORT
#  define OPENCVINTERFACE_NO_EXPORT
#else
#  ifndef OPENCVINTERFACE_EXPORT
#    ifdef openCVInterface_EXPORTS
        /* We are building this library */
#      define OPENCVINTERFACE_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define OPENCVINTERFACE_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef OPENCVINTERFACE_NO_EXPORT
#    define OPENCVINTERFACE_NO_EXPORT 
#  endif
#endif

#ifndef OPENCVINTERFACE_DEPRECATED
#  define OPENCVINTERFACE_DEPRECATED __declspec(deprecated)
#endif

#ifndef OPENCVINTERFACE_DEPRECATED_EXPORT
#  define OPENCVINTERFACE_DEPRECATED_EXPORT OPENCVINTERFACE_EXPORT OPENCVINTERFACE_DEPRECATED
#endif

#ifndef OPENCVINTERFACE_DEPRECATED_NO_EXPORT
#  define OPENCVINTERFACE_DEPRECATED_NO_EXPORT OPENCVINTERFACE_NO_EXPORT OPENCVINTERFACE_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef OPENCVINTERFACE_NO_DEPRECATED
#    define OPENCVINTERFACE_NO_DEPRECATED
#  endif
#endif

#endif /* OPENCVINTERFACE_EXPORT_H */
