
#ifndef FOURIERPLUGIN001_EXPORT_H
#define FOURIERPLUGIN001_EXPORT_H

#ifdef FOURIERPLUGIN001_STATIC_DEFINE
#  define FOURIERPLUGIN001_EXPORT
#  define FOURIERPLUGIN001_NO_EXPORT
#else
#  ifndef FOURIERPLUGIN001_EXPORT
#    ifdef fourierPlugin001_EXPORTS
        /* We are building this library */
#      define FOURIERPLUGIN001_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define FOURIERPLUGIN001_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef FOURIERPLUGIN001_NO_EXPORT
#    define FOURIERPLUGIN001_NO_EXPORT 
#  endif
#endif

#ifndef FOURIERPLUGIN001_DEPRECATED
#  define FOURIERPLUGIN001_DEPRECATED __declspec(deprecated)
#endif

#ifndef FOURIERPLUGIN001_DEPRECATED_EXPORT
#  define FOURIERPLUGIN001_DEPRECATED_EXPORT FOURIERPLUGIN001_EXPORT FOURIERPLUGIN001_DEPRECATED
#endif

#ifndef FOURIERPLUGIN001_DEPRECATED_NO_EXPORT
#  define FOURIERPLUGIN001_DEPRECATED_NO_EXPORT FOURIERPLUGIN001_NO_EXPORT FOURIERPLUGIN001_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef FOURIERPLUGIN001_NO_DEPRECATED
#    define FOURIERPLUGIN001_NO_DEPRECATED
#  endif
#endif

#endif /* FOURIERPLUGIN001_EXPORT_H */
